
version: '3.7'

services:
  trawler:
    container_name: trawler.all
    ports:
      - 3000:3000
      - 8080:8080
    build:
      context: .
    volumes:
        - ./data:/app/trawler/data  
  tor:
    image: osminogin/tor-simple
    restart: always
    ports:
      - 9050:9050
